### ISSUE TITLE
Error "date string could not be parsed" al abrir archivo .osm en JOSM

### ISSUE THREAD

**Issue by rodrigorega** [AnderPijoan/cat2osm2#13]
Hola.
Al abrir desde JOSM un archivo .osm generado con Cat2Osm2 obtengo el siguiente mensaje de error:

![image](https://cloud.githubusercontent.com/assets/3441785/13732124/4951c06c-e97b-11e5-9ff9-91ea1437d239.png)

En consola obtengo esto:
> INFO: Open file: /home/user/Descargas/final-68326-.osm (31711 bytes)
> ERROR: org.openstreetmap.josm.io.IllegalDataException: org.openstreetmap.josm.tools.UncheckedParseException: The date string (2016-03-13 15:34:52.911) could not be parsed.. Cause: org.openstreetmap.josm.tools.UncheckedParseException: The date string (2016-03-13 15:34:52.911) could not be parsed.
> org.openstreetmap.josm.io.IllegalDataException: org.openstreetmap.josm.tools.UncheckedParseException: The date string (2016-03-13 15:34:52.911) could not be parsed.
>         at org.openstreetmap.josm.io.OsmReader.doParseDataSet(OsmReader.java:654)
>         at org.openstreetmap.josm.io.OsmReader.parseDataSet(OsmReader.java:672)
>         at org.openstreetmap.josm.io.OsmImporter.parseDataSet(OsmImporter.java:132)
>         at org.openstreetmap.josm.io.OsmImporter.loadLayer(OsmImporter.java:122)
>         at org.openstreetmap.josm.io.OsmImporter.importData(OsmImporter.java:91)
>         at org.openstreetmap.josm.io.OsmImporter.importData(OsmImporter.java:76)
>         at org.openstreetmap.josm.io.FileImporter.importDataHandleExceptions(FileImporter.java:91)
>         at org.openstreetmap.josm.actions.OpenFileAction$OpenFileTask.importData(OpenFileAction.java:364)
>         at org.openstreetmap.josm.actions.OpenFileAction$OpenFileTask.realRun(OpenFileAction.java:317)
>         at org.openstreetmap.josm.gui.PleaseWaitRunnable.doRealRun(PleaseWaitRunnable.java:93)
>         at org.openstreetmap.josm.gui.PleaseWaitRunnable.run(PleaseWaitRunnable.java:161)
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:262)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
>         at java.lang.Thread.run(Thread.java:745)
> Caused by: org.openstreetmap.josm.tools.UncheckedParseException: The date string (2016-03-13 15:34:52.911) could not be parsed.
>         at org.openstreetmap.josm.tools.date.DateUtils.tsFromString(DateUtils.java:139)
>         at org.openstreetmap.josm.io.OsmReader.readCommon(OsmReader.java:457)
>         at org.openstreetmap.josm.io.OsmReader.parseNode(OsmReader.java:213)
>         at org.openstreetmap.josm.io.OsmReader.parseOsm(OsmReader.java:158)
>         at org.openstreetmap.josm.io.OsmReader.parseRoot(OsmReader.java:120)
>         at org.openstreetmap.josm.io.OsmReader.parse(OsmReader.java:106)
>         at org.openstreetmap.josm.io.OsmReader.doParseDataSet(OsmReader.java:621)
>         ... 15 more

Info de sistema:

> $ java -jar josm-latest.jar --version
> JOSM/1.5 (9979 es) Linux Debian GNU/Linux 8.3 (jessie)
>
> $ java -jar cat2osm2.jar -v
> Cat2Osm2 versión 2014-10-14.
> 
> $ java -version
> java version "1.7.0_95"
> OpenJDK Runtime Environment (IcedTea 2.6.4) (7u95-2.6.4-1~deb8u1)
> OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)

También me consta que pasa el mismo problema en Windows. Parece que alguna actualización de JOSM ha roto la compatibilidad con Cat2Osm2, no podría detallar en qué versión o fecha concreta ha pasado esto.

Un saludo.

**Comment by moiarcsan** [comment]
@AnderPijoan Buenos días, a mi me ocurre lo mismo al realizar la conversión para los shapes de Sevilla capital, cuando intento importarlo en JOSM me salta el mismo error.

**Comment by soymano** [comment]
Hola,

Yo abrí ayer una incidencia en JOSM (#12622) y me contestaron que con la nueva versión de JOSM (99xx) son más estrictos en la validación de las fechas.
Y me remitieron a solucionarlo a través de cat2osm2.

La pega está en que cat2osm2 genera los ficheros OSM con los puntos con un timestamp en un formato (2016-03-13 15:34:52.911 simulo el que ha puesto @rodrigorega en su mensaje) y ahora JOSM lo quiere en otro (2016-03-13T15:34:52Z).

Total, creo que una tontería para JOSM, ya que en anteriores versiones se cargaban sin problemas los OSM de cat2osm2. Pero que obligan a que la corrección sea a través de cambiar cat2osm2.

saludos,

**Comment by moiarcsan** [comment]
@soymano Hay alguna posibilidad de introducir esos cambios en cat2osm2, ya que necesito que me abra los ficheros de una conversión realizada para este miércoles.
Otra opción es emplear una versión más antigua a la que comentas de JOSM no?, ¿Alguna idea de cómo puedo realizar eso?

**Comment by soymano** [comment]
@moiarcsan Para saber cual era el error, yo edité un OSM de cat2osm2 (extre el fichero OSM que hay dentro de cada GZ) y me puse con paciencia a cambiar el formato de todos los timestamp que tenía dentro. Luego abres ese OSM corregido con JOSM y funciona perfectamente.
Si son muchos ficheros los que quieres subir, esto es misión imposible.

Otra buena opción es instalar un JOSM versión 93xx o anterior y no utilizar la versión "launch". Hasta hace un par de semanas, esta versión me funcionaba muy bien. Al arrancar te dará un aviso de que debes actualizarte, pero no se si luego te deja o impide subir los datos.
La pega ahora es encontrar un fichero de instalación de una versión 993xx ...  a primera vista, no lo he encontrado por su web.

**Comment by soymano** [comment]
@moiarcsan encontrado. La versión 9329 es la última que me funcionó bien con los ficheros de cat2osm2:
https://josm.openstreetmap.de/download/windows/

**Comment by moiarcsan** [comment]
@soymano Muchas gracias, ya encontré los jar de las versiones anteriores aquí [1] y ejecutando por consola el comando java -jar archivo.jar me funcionó, ahora sólo debo encontrar una versión en la que no me valide la fecha tal y como hace ahora.

[1] https://josm.openstreetmap.de/download/

**Comment by moiarcsan** [comment]
@soymano Muchas gracias, lo voy a probar!!!

**Comment by alejandroscf** [comment]
Hola, 
Otra solución chapucera es borrar los valores de timestamp de los ficheros .osm Parece que JOSM los lee bien aunque el campo esté vacío.
Una vez descomprimidos (con `unp *osm.gz` por ejemplo) `sed` hace le trabajo por nosotros en todos los ficheros del directorio actual:
`for i in *.osm; do sed -i.orig 's/timestamp="[^"]*"/timestamp=""/g' $i ;done`

Saludos,
Alejandro

**Comment by AnderPijoan** [comment]
Creo que ya está arreglado. Espero no haberme cargado nada por el camino. En cuanto saque tiempo intento ponerme con los otros issues.

Gracias y Saludos.

**Comment by rogorido** [comment]
perdón, pero a mí con la versión del 9 de junio y josm 10526 me sigue saliendo el error... ¿a todos se les ha solucionado?

**Comment by rodrigorega** [comment]
@rogorido A mi también me sigue saliendo el error. Estoy borrando los timestamps con script.

**Comment by rogorido** [comment]
@rodrigorega Sí, el loop de @alejandroscf funciona bien. Con eso vale en principio.

**Comment by Raulvo** [comment]
JOSM sigue devolviendo error. También hice un script para corregir las fechas. Dejando sólo mes y año JOSM lo abre.
