### ISSUE TITLE
No funcionan los archivos de cat2osm2 con Josm

### ISSUE THREAD

**Issue by javiermrr** [AnderPijoan/cat2osm2#14]
Me da este error al abrir los archivos:

> Identification: JOSM/1.5 (10966 es) Windows 10 64-Bit
> Memory Usage: 423 MB / 910 MB (256 MB allocated, but free)
> Java version: 1.8.0_111-b14, Oracle Corporation, Java HotSpot(TM) 64-Bit Server VM
> Screen: \Display0 1920x1080
> Maximum Screen Size: 1920x1080
> VM arguments: [-Djava.security.manager, -Djava.security.policy=file:<java.home>\lib\security\javaws.policy, -DtrustProxy=true, -Djnlpx.home=<java.home>\bin, -Djnlpx.origFilenameArg=%UserProfile%\Desktop\josm.jnlp, -Djnlpx.remove=true, -Djava.util.Arrays.useLegacyMergeSort=true, -Djnlpx.splashport=52478, -Djnlpx.jvm=<java.home>\bin\javaw.exe, -Djnlpx.vmargs=LURqYXZhLnV0aWwuQXJyYXlzLnVzZUxlZ2FjeU1lcmdlU29ydD10cnVlAA==]
> 
> Plugins:
> - FixAddresses (32796)
> - apache-commons (32699)
> - ejml (32680)
> - geotools (32813)
> - jts (32699)
> - opendata (32898)
> - utilsplugin2 (32815)
> 
> Map paint styles:
> - https://josm.openstreetmap.de/josmfile?page=Styles/Coloured_Streets&zip=1
> 
> === REPORTED CRASH DATA ===
> BugReportExceptionHandler#handleException:
> No data collected.
> 
> Warning issued by: BugReportExceptionHandler#handleException
> 
> === STACK TRACE ===
> Thread: AWT-EventQueue-2 (55) of javawsApplicationThreadGroup
> org.openstreetmap.josm.tools.UncheckedParseException: The date string (2016-10-30T12:38+0100) could not be parsed.
>   at org.openstreetmap.josm.tools.date.DateUtils.tsFromString(DateUtils.java:153)
>   at org.openstreetmap.josm.io.OsmReader.readCommon(OsmReader.java:457)
>   at org.openstreetmap.josm.io.OsmReader.parseNode(OsmReader.java:215)
>   at org.openstreetmap.josm.io.OsmReader.parseOsm(OsmReader.java:160)
>   at org.openstreetmap.josm.io.OsmReader.parseRoot(OsmReader.java:122)
>   at org.openstreetmap.josm.io.OsmReader.parse(OsmReader.java:108)
>   at org.openstreetmap.josm.io.OsmReader.doParseDataSet(OsmReader.java:592)
>   at org.openstreetmap.josm.io.OsmReader.parseDataSet(OsmReader.java:643)
>   at org.openstreetmap.josm.io.OsmImporter.parseDataSet(OsmImporter.java:123)
>   at org.openstreetmap.josm.io.OsmImporter.loadLayer(OsmImporter.java:113)
>   at org.openstreetmap.josm.io.OsmImporter.importData(OsmImporter.java:90)
>   at org.openstreetmap.josm.io.OsmImporter.importData(OsmImporter.java:75)
>   at org.openstreetmap.josm.io.FileImporter.importDataHandleExceptions(FileImporter.java:90)
>   at org.openstreetmap.josm.actions.OpenFileAction$OpenFileTask.importData(OpenFileAction.java:349)
>   at org.openstreetmap.josm.actions.OpenFileAction$OpenFileTask.realRun(OpenFileAction.java:302)
>   at org.openstreetmap.josm.gui.PleaseWaitRunnable.doRealRun(PleaseWaitRunnable.java:93)
>   at org.openstreetmap.josm.gui.PleaseWaitRunnable.run(PleaseWaitRunnable.java:141)
>   at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
>   at java.util.concurrent.FutureTask.run(Unknown Source)
>   at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
>   at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
>   at java.lang.Thread.run(Unknown Source)
> Caused by: java.lang.IllegalArgumentException: 2016-10-30T12:38+0100
>   at com.sun.org.apache.xerces.internal.jaxp.datatype.XMLGregorianCalendarImpl$Parser.skip(Unknown Source)
>   at com.sun.org.apache.xerces.internal.jaxp.datatype.XMLGregorianCalendarImpl$Parser.parse(Unknown Source)
>   at com.sun.org.apache.xerces.internal.jaxp.datatype.XMLGregorianCalendarImpl.<init>(Unknown Source)
>   at com.sun.org.apache.xerces.internal.jaxp.datatype.DatatypeFactoryImpl.newXMLGregorianCalendar(Unknown Source)
>   at org.openstreetmap.josm.tools.date.DateUtils.tsFromString(DateUtils.java:151)
>   ... 21 more
> }}}
>

**Comment by AnderPijoan** [comment]
La nueva versión he pasado el TimeStamp a solo fecha sin hora. A mi si que ahora me funciona a ver si a los demás también. Saludos.

**Comment by javiermrr** [comment]
Ahora los archivos no aparecen en la carpeta resultados dando este error en la consola de Windows 10:

> [2016-12-02 14:06:23.641] Leyendo archivo Cat urbano.
> [2016-12-02 14:06:25.558] Leyendo archivo Cat rústico.
> [2016-12-02 14:06:26.359] Moviendo puntos de entrada a sus parcelas mas cercanas.
> Exception in thread "main" java.lang.reflect.InvocationTargetExceptiondo = 0 horas, 0 minutos, 0 segundos..
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
>         at java.lang.reflect.Method.invoke(Unknown Source)
>         at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
> Caused by: java.lang.NullPointerException
>         at com.vividsolutions.jts.linearref.LinearLocation.<init>(LinearLocation.java:118)
>         at com.vividsolutions.jts.linearref.LocationIndexOfPoint.indexOfFromStart(LocationIndexOfPoint.java:147)
>         at com.vividsolutions.jts.linearref.LocationIndexOfPoint.indexOf(LocationIndexOfPoint.java:74)
>         at com.vividsolutions.jts.linearref.LocationIndexOfPoint.indexOf(LocationIndexOfPoint.java:51)
>         at com.vividsolutions.jts.linearref.LocationIndexedLine.project(LocationIndexedLine.java:185)
>         at Cat2Osm.moveEntrancesToParcel(Cat2Osm.java:170)
>         at Main.ejecutarCat2Osm(Main.java:328)
>         at Main.main(Main.java:117)
>         ... 5 more

**Comment by javiermrr** [comment]
Funciona perfectamente. He vuelto a descargar los archivos del catastro y todo perfecto.

Buen trabajo :)

Un saludo.
